name: 1453-ai-telegram-bot
services:
  - name: app
    image: 1453-ai-telegram-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - YOUTUBE_CHANNEL_ID=${YOUTUBE_CHANNEL_ID}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_IDS=${TELEGRAM_CHAT_IDS}
      - PLATFORM_LINKS=${PLATFORM_LINKS}
      - PORT=3000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - LOG_LEVEL=info
      - REDIS_URL=${REDIS_URL}
      - BASE_URL=${BASE_URL}
    volumes:
      - ./logs:/app/logs
    health_check:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    resources:
      limits:
        memory: 512M
        cpus: '0.5'
      reservations:
        memory: 256M
        cpus: '0.25'